module.exports = {
  env: {
    REACT_APP_API_KEY: '1',
    REACT_APP_AUTH_DOMAIN: '2',
    REACT_APP_PROJECT_ID: '3',
    REACT_APP_STORAGE_BUCKET: '4',
    REACT_APP_MESSAGING_SENDER_ID: '5',
    REACT_APP_APP_ID: '6',
    REACT_APP_MEASUREMENT_ID: '7'
  },
}
